# apiVersion: v1
# kind: Service
# metadata:
#   name: AngularApp-Service
# spec:
#   selector:
#     app: AngularApp
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8084

apiVersion: v1
kind: Service
metadata:
  name: angularapp-service
spec:
  selector:
    app: angularapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084

